version: '3.8'

services:
  input-csv-file-processing-svc:
    build:
      dockerfile: input-csv-file-processing-svc/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./data/csv:/app/csv:rw
    depends_on:
      - postgres

  payments-processing-svc:
    build:
      dockerfile: payments-processing-svc/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres

  payment-status-svc:
    build:
      dockerfile: payment-status-svc/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - postgres

  data-persistence-svc:
    build:
      dockerfile: data-persistence-svc/Dockerfile
    ports:
      - "8085:8085"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/payments
      - QUARKUS_DATASOURCE_USERNAME=user
      - QUARKUS_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres

  output-csv-file-processing-svc:
    build:
      dockerfile: output-csv-file-processing-svc/Dockerfile
    ports:
      - "8084:8084"
    volumes:
      - ./data/csv:/app/csv:rw
    depends_on:
      - postgres

  orchestrator-svc:
    build:
      dockerfile: orchestrator-svc/Dockerfile
    environment:
      - CSV_FOLDER_PATH=/app/csv
      - PROCESS_CSV_PAYMENTS_INPUT_FILE_SVC_HOST=input-csv-file-processing-svc
      - PROCESS_CSV_PAYMENTS_INPUT_FILE_SVC_PORT=8081
      - PERSIST_PAYMENT_RECORD_SVC_HOST=data-persistence-svc
      - PERSIST_PAYMENT_RECORD_SVC_PORT=8085
      - SEND_PAYMENT_RECORD_SVC_HOST=payments-processing-svc
      - SEND_PAYMENT_RECORD_SVC_PORT=8082
      - PERSIST_ACK_PAYMENT_SENT_SVC_HOST=data-persistence-svc
      - PERSIST_ACK_PAYMENT_SENT_SVC_PORT=8085
      - PROCESS_ACK_PAYMENT_SENT_SVC_HOST=payments-processing-svc
      - PROCESS_ACK_PAYMENT_SENT_SVC_PORT=8082
      - PROCESS_PAYMENT_STATUS_SVC_HOST=payment-status-svc
      - PROCESS_PAYMENT_STATUS_SVC_PORT=8083
      - PROCESS_CSV_PAYMENTS_OUTPUT_FILE_SVC_HOST=output-csv-file-processing-svc
      - PROCESS_CSV_PAYMENTS_OUTPUT_FILE_SVC_PORT=8084
    volumes:
      - ./data/csv:/app/csv:rw
    depends_on:
      - input-csv-file-processing-svc
      - payments-processing-svc
      - payment-status-svc
      - output-csv-file-processing-svc
      - postgres

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=payments
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
