appName: "Customer Data Pipeline"
basePackage: "com.example.customer"
steps:
  - name: "ProcessCustomer"
    cardinality: "ONE_TO_ONE"
    inputTypeName: "CustomerInput"
    inputFields:
      - name: "id"
        type: "UUID"
        protoType: "string"
      - name: "name"
        type: "String"
        protoType: "string"
      - name: "email"
        type: "String"
        protoType: "string"
    outputTypeName: "CustomerOutput"
    outputFields:
      - name: "id"
        type: "UUID"
        protoType: "string"
      - name: "name"
        type: "String"
        protoType: "string"
      - name: "status"
        type: "String"
        protoType: "string"
      - name: "processedAt"
        type: "String"
        protoType: "string"
  - name: "ValidateOrder"
    cardinality: "EXPANSION"
    inputTypeName: "OrderInput"
    inputFields:
      - name: "orderId"
        type: "String"
        protoType: "string"
      - name: "items"
        type: "String"
        protoType: "string"
    outputTypeName: "OrderItem"
    outputFields:
      - name: "itemId"
        type: "String"
        protoType: "string"
      - name: "valid"
        type: "Boolean"
        protoType: "bool"