---
appName: "Sample Pipeline App"
basePackage: "com.example.sample"
steps:
- stepType: "StepOneToOne"
  serviceNameCamel: "processCustomer"
  serviceName: "process-customer-svc"
  cardinality: "ONE_TO_ONE"
  inputFields:
  - protoType: "string"
    name: "id"
    type: "UUID"
  - protoType: "string"
    name: "name"
    type: "String"
  - protoType: "string"
    name: "email"
    type: "String"
  - protoType: "string"
    name: "createdAt"
    type: "LocalDateTime"
  outputFields:
  - protoType: "string"
    name: "id"
    type: "UUID"
  - protoType: "string"
    name: "name"
    type: "String"
  - protoType: "string"
    name: "status"
    type: "String"
  - protoType: "string"
    name: "processedAt"
    type: "String"
  outputTypeName: "CustomerOutput"
  inputTypeName: "CustomerInput"
  outputTypeSimpleName: "CustomerOutput"
  grpcClientName: "ProcessCustomerSvc"
  name: "Process Customer"
  inputTypeSimpleName: "CustomerInput"
  order: 1
- stepType: "StepOneToOne"
  serviceNameCamel: "validateOrder"
  serviceName: "validate-order-svc"
  cardinality: "ONE_TO_ONE"
  inputFields:
  - protoType: "string"
    name: "id"
    type: "UUID"
  - protoType: "string"
    name: "name"
    type: "String"
  - protoType: "string"
    name: "status"
    type: "String"
  - protoType: "string"
    name: "processedAt"
    type: "String"
  outputFields:
  - protoType: "string"
    name: "id"
    type: "UUID"
  - protoType: "bool"
    name: "isValid"
    type: "Boolean"
  outputTypeName: "ValidationOutput"
  inputTypeName: "CustomerOutput"
  outputTypeSimpleName: "ValidationOutput"
  grpcClientName: "ValidateOrderSvc"
  name: "Validate Order"
  inputTypeSimpleName: "CustomerOutput"
  order: 2
