appName: "sample-pipeline-app"
basePackage: "com.example.sample"
steps:
  - name: "Process Customer"
    cardinality: "EXPANSION"
    inputTypeName: "CustomerInput"
    inputFields:
      - name: "id"
        type: "String"
        protoType: "string"
      - name: "customerId"
        type: "String"
        protoType: "string"
      - name: "name"
        type: "String"
        protoType: "string"
    outputTypeName: "CustomerOutput"
    outputFields:
      - name: "id"
        type: "String"
        protoType: "string"
      - name: "customerId"
        type: "String"
        protoType: "string"
      - name: "processedName"
        type: "String"
        protoType: "string"
  - name: "Validate Order"
    cardinality: "ONE_TO_ONE"
    inputTypeName: "OrderInput"
    inputFields:
      - name: "id"
        type: "String"
        protoType: "string"
      - name: "orderId"
        type: "String"
        protoType: "string"
      - name: "amount"
        type: "Double"
        protoType: "double"
    outputTypeName: "OrderOutput"
    outputFields:
      - name: "id"
        type: "String"
        protoType: "string"
      - name: "orderId"
        type: "String"
        protoType: "string"
      - name: "validated"
        type: "Boolean"
        protoType: "bool"