quarkus:
  picocli:
    top-command: com.example.poc.client.CsvCommand
  datasource:
    jdbc:
      url: jdbc:h2:mem:poc;DB_CLOSE_ON_EXIT=FALSE
      driver: org.h2.Driver
    username: sa
    password: ""
  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: false

csv-poc:
  payment-provider:
    permits-per-second: 10.0
    timeout-millis: 5000
