spring:
  main:
    web-application-type: NONE
  datasource:
    url: jdbc:h2:mem:poc;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: 'create-drop'
    #show-sql: true
    properties:
      format_sql: true
  h2:
    console:
      enabled: true

api:



