spring:
  datasource:
    #url: jdbc:h2:file:/Users/mari/poc
    url: jdbc:h2:mem:poc
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: 'create-drop'
      show-sql: true
  h2:
    console:
      enabled: true
