spring:
  main:
    web-application-type: NONE
  datasource:
    url: jdbc:h2:mem:poc;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    properties:
      format_sql: true
  h2:
    console:
      enabled: true

#api:
#  url: 'http://127.0.0.1:7902'
#  account:
#  apiKey:
