appName: DigestivePipeline
basePackage: com.example.digestive

steps:
  - name: MouthStage
    cardinality: ONE_TO_ONE
    inputTypeName: FoodItem
    inputFields:
      - { name: id, type: UUID, protoType: string }
      - { name: name, type: String, protoType: string }
      - { name: massGrams, type: Double, protoType: double }
      - { name: composition, type: "Map<String, Double>", protoType: "map<string, double>" }
    outputTypeName: Bolus
    outputFields:
      - { name: id, type: UUID, protoType: string }
      - { name: contents, type: "List<String>", protoType: string }
      - { name: chewedMass, type: Double, protoType: double }
      - { name: salivaEnzymes, type: "List<String>", protoType: string }
    parallel: false

  - name: StomachStage
    cardinality: ONE_TO_ONE
    inputTypeName: Bolus
    inputFields:
      - { name: id, type: UUID, protoType: string }
      - { name: contents, type: "List<String>", protoType: string }
      - { name: chewedMass, type: Double, protoType: double }
      - { name: salivaEnzymes, type: "List<String>", protoType: string }
    outputTypeName: Chyme
    outputFields:
      - { name: id, type: UUID, protoType: string }
      - { name: nutrientMix, type: "Map<String, Double>", protoType: "map<string, double>" }
      - { name: acidLevel, type: Double, protoType: double }
      - { name: liquidity, type: Double, protoType: double }
    parallel: false

  - name: SmallIntestineStage
    cardinality: EXPANSION
    inputTypeName: Chyme
    inputFields:
      - { name: id, type: UUID, protoType: string }
      - { name: nutrientMix, type: "Map<String, Double>", protoType: "map<string, double>" }
      - { name: acidLevel, type: Double, protoType: double }
      - { name: liquidity, type: Double, protoType: double }
    outputTypeName: Nutrients
    outputFields:
      - { name: name, type: String, protoType: string }
      - { name: amountMg, type: Double, protoType: double }
      - { name: absorptionRate, type: Double, protoType: double }
    parallel: true

  - name: LargeIntestineStage
    cardinality: REDUCTION
    inputTypeName: Nutrients
    inputFields:
      - { name: name, type: String, protoType: string }
      - { name: amountMg, type: Double, protoType: double }
      - { name: absorptionRate, type: Double, protoType: double }
    outputTypeName: Residue
    outputFields:
      - { name: id, type: UUID, protoType: string }
      - { name: dryMatter, type: Double, protoType: double }
      - { name: remainingFiber, type: Double, protoType: double }
    batchSize: 20
    batchTimeoutMs: 1500
    parallel: false

  - name: RectumStage
    cardinality: ONE_TO_ONE
    inputTypeName: Residue
    inputFields:
      - { name: id, type: UUID, protoType: string }
      - { name: dryMatter, type: Double, protoType: double }
      - { name: remainingFiber, type: Double, protoType: double }
    outputTypeName: WasteProduct
    outputFields:
      - { name: id, type: UUID, protoType: string }
      - { name: massGrams, type: Double, protoType: double }
      - { name: emoji, type: String, protoType: string }
    parallel: false