FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0
WORKDIR /work/
RUN groupadd -r app && useradd -r -g app app
COPY --chmod=0755 target/*-runner /work/application
RUN chown app:app /work/application
EXPOSE 8080
USER app
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
