FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
WORKDIR /work/
RUN microdnf install shadow-utils && groupadd -r app && useradd -r -g app app
COPY --chmod=0755 target/quarkus-run.jar /work/application
RUN chown app:app /work/application
EXPOSE 8080
USER app
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]